Algoritmo "Exercisio 2 Area Trapezio"
// Autor             : Rafael Sousa
// Primeiro Update   : 20-07-2017
// Ultimo Update     : 20-07-2017
// Versao Atual      : Mark 1
Var
   BaseM,BaseM2,Altura,AreaT:real
Inicio
   Escreva("Insira as bases e a altura: ")
    leia(BaseM,BaseM2,Altura)
     AreaT <-(BaseM+BaseM2)*Altura/2
   Escreva("A area do Trapezio e:")
    Escreva(AreaT)


Fimalgoritmo