Algoritmo "Exercisio 13 PrecoKilo"
// Autor           : Rafael Sousa
// Primeiro Update : 09-09-2017
// Ultimo Update   : 09-09-2017
// Versao Atual    : Mk 1
Var
  Preco:real
  Peso:real
  Kilos:real
  ValorFinal:real
Inicio
  Escreva("Insira o preco do produto ")
   Leia(Preco)
  Escreva("Insira a quantida de kilos que quer comprar ")
   Leia(Kilos)
    ValorFinal<-Preco*Kilos
     Escreva(ValorFinal)
  Fimalgoritmo

  

Fimalgoritmo