Algoritmo "Exercisio 1 Area Retangulo"
// Autor           : Rafael Sousa
// Primeiro Update : 09-09-2017
// Ultimo Update   : 09-09-2017
// Versao Atual    : Mk 1
Var
  Altura:real
  Largura:real
  AreaR:real
Inicio
  Escreva("Insira a altura e a largura retangulo: ")
   Leia(Altura)
    Leia(Largura)
  AreaR<-Altura*Largura
  Escreva("A area do retangulo é: ")
   Escreva(AreaR)
  Fimalgoritmo

  

Fimalgoritmo